---
- name: "Download tekton operator manifests"
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/tekton-releases/operator/latest/release.yaml
    dest: /tmp/tekton-operator.yml
    mode: 0644

- name: "Download tekton config manifests"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/tektoncd/operator/main/config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml
    dest: /tmp/tekton-config.yml
    mode: 0644

- name: Deploy tekton Application
  kubernetes.core.k8s:
    src: /tmp/tekton-operator.yml
    state: present

- name: Wait for tekton-operator to be ready
  kubernetes.core.k8s:
    wait: true
    wait_sleep: 10
    wait_condition:
      type: Available
      status: "True"
    namespace: tekton-operator
    kind: Deployment
    name: tekton-operator
    version: apps/v1
  retries: 30

- name: Deploy tekton Application
  kubernetes.core.k8s:
    src: /tmp/tekton-config.yml
    state: present

- name: Wait for tekton-dashboard to be ready
  kubernetes.core.k8s:
    wait: true
    wait_sleep: 10
    wait_condition:
      type: Available
      status: "True"
    namespace: tekton-pipelines
    kind: Deployment
    name: tekton-dashboard
    version: apps/v1
  retries: 30
